-- ÖRNEK wp_posts INSERT'leri

-- INSERT 1
INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(2, 1, '2018-02-28 17:37:56', '2018-02-28 14:37:56', '<p>[contact-form-7 id="1183" title="İletişim Formu"]</p>\n\n<!-- wp:paragraph -->\n<p></p>\n<!-- /wp:paragraph -->', 'İletişim', '', 'publish', 'closed', 'open', '', 'iletisim', '', '', '2020-12-07 11:41:08', '2020-12-07 08:41:08', '', 0, 'http://hayattan.net/?page_id=2', 0, 'page', '', 0),
(1189, 1, '2020-12-11 23:40:49', '2020-12-11 20:40:49', '<!-- wp:paragraph -->\n<p> çcçcüc</p>\n<!-- /wp:paragraph -->', '', '', 'inherit', 'closed', 'closed', '', '1188-revision-v1', '', '', '2020-12-11 23:40:49', '2020-12-11 20:40:49', '', 1188, 'http://hayattan.net/1188-revision-v1/', 0, 'revision', '', 0),
(1506, 1, '2021-02-08 11:03:03', '2021-02-08 08:03:03', '<!-- wp:paragraph -->\n<p>&nbsp;

-- INSERT 2
INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(1298, 1, '2020-12-29 15:56:03', '2020-12-29 12:56:03', '<!-- wp:paragraph -->\n<p>“ Uzun ince bir yoldayım” Diyor hayatı uzun ince bir yol olarak tanımlıyor saz üstadı, halk ozanı Âşık Veysel. Aşık Veysel’in de dediği gibi hayat denilen şey uzun ince bir yolculuktur. Kimi zaman zorlu kimi zaman kolay. Bugün sizlerle uzun ince bir yolu hakkıyla yürüyebilen, düşüp kalkabilen, pes etmeyen bir insanın hikâyesini ve dahası Behçet hastalığını konuşacağız. Sözü fazlada &nbsp;

-- INSERT 3
INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(985, 1, '2020-10-27 00:03:53', '2020-10-26 21:03:53', '<!-- wp:paragraph -->\n<p>Kaldırımlar... O şiiri hatırlıyorum.&nbsp;

-- INSERT 4
INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(1267, 1, '2020-12-24 18:49:36', '2020-12-24 15:49:36', '<!-- wp:paragraph -->\n<p>Ben Konya’dan Ömer Tanır</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>1989 Konya doğumluyum.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Konya da ikamet eden bir vatandaşım.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Bu kaleme aldığım ilk yazım.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>2003 yılında biri bana Behçet hastalığı tanısı konduğunda sen bu hastalık hakkında yazı yazacaksın insanları çektiğin sıkıntılardan dolayı bilgilendireceksin deseydi herhalde geleceği yanlış görüyorsun der veya o günkü çocuk halimi de baz alacak olursam güler geçerdim.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Çocukluğumda kıpır kıpır yerinde duramayan bir çocuk dolduğum için doğrusunu söylemek gerekirse komşularımız tarafından sürekli anneme şikâyete gelinen bir çocuktum.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Bir gün yine çocukluk arkadaşlarım ile oyun oynarken birden yumurtalıklarımın ağrıması sebebiyle yere düşüp kaldım.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Hemen hastaneye götürdüler gerçek şu ki o gün e kadar hastaneyi sadece evimizin yakınında olduğu için oyun olarak &nbsp;

-- INSERT 5
INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(1437, 1, '2021-01-17 16:30:09', '2021-01-17 13:30:09', '<!-- wp:paragraph -->\n<p>Yaşamın içinde birçok fırsat olduğu gibi, tehditler de bulunmaktadır. Bunların, çoğu zaman farkına bile varmayız. Bilgisine vakıf olduğumuz fırsat ve tehditlere, imkanlarımız dahilinde tutum alır ve ona göre hareket ederiz. Mesela, bir deniz kenarında yürüyorsak ve suda çırpınan birine rastladıysak, ona yardım edebilir, onu bu durumdan kurtarabiliriz. Denizin elverişsiz olması bizim için tehdit teşkil ediyorsa da yardımcı olabilecek başka imkanları araştırırız. Belki bu insan, hayatımızı değiştirebilecektir, bunu hiçbirimiz bilemeyiz. Kitaplara yönelik bir ilgimiz varsa ve günün birinde bir yazarla yolumuz kesiştiğinde, belki onunla bir sohbet imkânı bulabilir, yeni fikirler, yeni ufuklar kazanma şansına sahip olabiliriz. Emlak veya otomobillere merakımız varsa da bunların ticaretiyle ilgili bir fırsat ayağımıza geldiğinde de bunu kendimiz için olumlu şekilde değerlendirebiliriz. Bunlardan herhangi birine ilgimiz yoksa, fırsat yanımızda durduğu halde onu göremez ve değerlendiremeyiz. İlgi alanlarımızı ve insan kaynaklarımızı genişletmediğimiz müddetçe, oturduğumuz yerden çoğu zaman hiçbir şey ayağımıza gelmez.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Bazen de elimizdekiyle yetinmeyi tercih ettiğimiz zamanlar olabilir. Halbuki elimizdekinden daha iyisine ulaşma imkânı bir adım ötemizdedir. Az bir çabayla dahi ulaşabileceğimiz bu fırsata bakarken, acaba bu fırsata uzanırken elimdekini kaybeder miyim korkusu da yaşayabiliriz. O fırsata uzansak belki daha da iyilerini görme imkânımız olacaktır. Bir kapıyı açmadan öteki kapıyı nasıl ki göremiyorsak, yanımızda duran ve iyi olduğuna inandığımız fırsatları değerlendirmekte de de cüretkâr davranabilmeliyiz. Bilindiği üzere, Dimyat''a pirince giderken evdeki bulgurdan olmayalım diye önemli bir atasözümüz vardır. Eldekini kaybetmek ne kadar kötü bir durum olsa da unutmayalım ki mutlu bir şekilde Dimyat’tan dönenler de hepimizin malumudur.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Mehmet Hüseyinçelebi 16.01.2021 Kastamonu</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Ya çapın kadar hareket edeceksin ya da çapını büyüteceksin.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Mehmet Hüseyinçelebi</p>\n<!-- /wp:paragraph -->', 'DİMYAT’TAN DÖNENLER', '', 'inherit', 'closed', 'closed', '', '1436-revision-v1', '', '', '2021-01-17 16:30:09', '2021-01-17 13:30:09', '', 1436, 'http://hayattan.net/1436-revision-v1/', 0, 'revision', '', 0),
(1330, 1, '2021-01-02 11:30:45', '2021-01-02 08:30:45', '<!-- wp:image {"id":1326,"sizeSlug":"large","linkDestination":"none"} -->\n<figure class="wp-block-image size-large"><img src="http://hayattan.net/wp-content/uploads/IMG_20210101_210918_040.jpg" alt="" class="wp-image-1326"/></figure>\n<!-- /wp:image -->\n\n<!-- wp:paragraph -->\n<p><br>Hayatın kendisini tam da içinde hissedenler;

