-- WordPress to Neon Import
-- Prepared for Hayattan.Net
-- Date: 2026-02-10T01:53:48.438Z

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- WordPress Posts (Published only)
INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(2, 1, '2018-02-28 17:37:56', '2018-02-28 14:37:56', '<p>[contact-form-7 id="1183" title="İletişim Formu"]</p>\n\n<!-- wp:paragraph -->\n<p></p>\n<!-- /wp:paragraph -->', 'İletişim', '', 'publish', 'closed', 'open', '', 'iletisim', '', '', '2020-12-07 11:41:08', '2020-12-07 08:41:08', '', 0, 'http://hayattan.net/?page_id=2', 0, 'page', '', 0),
(1189, 1, '2020-12-11 23:40:49', '2020-12-11 20:40:49', '<!-- wp:paragraph -->\n<p> çcçcüc</p>\n<!-- /wp:paragraph -->', '', '', 'inherit', 'closed', 'closed', '', '1188-revision-v1', '', '', '2020-12-11 23:40:49', '2020-12-11 20:40:49', '', 1188, 'http://hayattan.net/1188-revision-v1/', 0, 'revision', '', 0),
(1506, 1, '2021-02-08 11:03:03', '2021-02-08 08:03:03', '<!-- wp:paragraph -->\n<p>&nbsp;

INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(1298, 1, '2020-12-29 15:56:03', '2020-12-29 12:56:03', '<!-- wp:paragraph -->\n<p>“ Uzun ince bir yoldayım” Diyor hayatı uzun ince bir yol olarak tanımlıyor saz üstadı, halk ozanı Âşık Veysel. Aşık Veysel’in de dediği gibi hayat denilen şey uzun ince bir yolculuktur. Kimi zaman zorlu kimi zaman kolay. Bugün sizlerle uzun ince bir yolu hakkıyla yürüyebilen, düşüp kalkabilen, pes etmeyen bir insanın hikâyesini ve dahası Behçet hastalığını konuşacağız. Sözü fazlada &nbsp;

INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(985, 1, '2020-10-27 00:03:53', '2020-10-26 21:03:53', '<!-- wp:paragraph -->\n<p>Kaldırımlar... O şiiri hatırlıyorum.&nbsp;

-- WordPress Users
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES
(1, 'hayattan', 'fbbcc776b09ffd6ca643fa7f90743f51', 'wpntr', 'omerfarukkotay@gmail.com', 'http://www.hayattan.net', '2018-02-28 14:37:56', '', 0, 'Ömer Faruk KOTAY'),
(3, 'kubrakiziltoprak', '$P$B.COQdXx5mtFSmymmIW72sBKyHlaAw/', 'kubrakiziltoprak', 'kubrakiziltoprak@hayattan.net', 'http://hayattan.net', '2020-09-10 00:13:38', '', 0, 'KÜBRA KIZILTOPRAK'),
(7, 'WordPress', '$P$B3alSpGAmuRsPf8d5EBIelaQPbZiH..', 'wordpress', 'omertanir@hayattan.net', 'http://hayattan.net', '2020-12-08 20:31:40', '', 0, 'ÖMER TANIR'),
(15, 'Oznur Sahan', '$P$B6uORhafNBIvbaiAv9.ENggUTNU8OZ0', 'oznur-sahan', 'foznursahan@gmail.com', 'http://www.hayattan.net', '2021-06-23 10:17:28', '1624443448:$P$Bl1cTDQ0zrGmInLuevfrLXwCcpFWFq0', 0, 'Öznur Şahan'),
(21, 'Fethi Ahmet ONER', '$P$BbTsAmR2qpZytjkR.x6oW63TpNQ9BA1', 'fethi-ahmet-oner', 'fethiahmetoner@gmail.com', 'http://www.hayattan.net', '2023-10-23 16:48:37', '1698079717:$P$BX3JDUPzPQ7nUeo0jVwCqax46Sv5tf.', 0, 'Fethi Ahmet ÖNER'),
(18, 'Mesut Hekimhan', '$P$BH2erkoCSHo3n1/dE0SZT3krDSBq15.', 'mesut-hekimhan', 'mesuthan@gmail.com', 'http://www.hayattan.net', '2022-05-10 11:05:16', '1652180716:$P$BAFFwvU9jXb059WYCOuIBUWTTgqC3O.', 0, 'Mesut HEKİMHAN'),
(22, 'Osman Faruk BOZ', '$P$BOrhTOsfzXxlGmMGbSg5CAieptDAUE1', 'osman-faruk-boz', 'bzosman362@gmail.com', 'http://www.hayattan.net', '2024-06-12 15:32:27', '1718206347:$P$BOAiTMViq.PqGAqiuZoHNvHCR4fOAZ/', 0, 'Osman Faruk BOZ'),
(23, 'Zuhal Terlikli', '$P$B68iJGfXsZDmFiGc0pkHJYv.4Davzz1', 'zuhal-terlikli', 'zuhalterlikli76@hotmail.com', 'http://www.hayattan.net', '2025-02-02 22:14:54', '1738534494:$P$BoLe0SfhgDM7FbURdXd.MyD3F5RXjl1', 0, 'Zuhal Terlikli');

-- WordPress Terms (Categories)
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(1, 'Genel', 'genel', 0),
(2, 'Ana Sayfa', 'ana-sayfa', 0),
(3, 'İletişim', 'iletisim', 0),
(4, 'Tayfur', 'tayfur', 0),
(5, 'engelli', 'engelli', 0),
(6, 'mill', 'mill', 0),
(7, 'milli tenisci', 'milli-tenisci', 0),
(8, 'benim hikayem', 'benim-hikayem', 0),
(9, 'hayattan', 'hayattan', 0),
(10, 'onur can koca', 'onur-can-koca', 0),
(11, 'engelsiz şahsiyetler', 'engelsiz-sahsiyetler', 0),
(12, 'kübra', 'kubra', 0),
(13, 'kızıltoprak', 'kiziltoprak', 0),
(14, 'karikatör', 'karikator', 0),
(15, 'ben', 'ben', 0),
(16, 'im hikayem', 'im-hikayem', 0),
(17, 'karikatür', 'karikatur', 0),
(18, 'Yazarlar', 'yazarlar', 0),
(19, 'slider yazı', 'slider', 0),
(20, 'gülerken ağlayanlar', 'gulerken-aglayanlar', 0),
(21, 'fmf', 'fmf', 0),
(22, 'mavi kalem', 'mavi-kalem', 0),
(23, 'Benim Hikayem', 'benim-hikayem', 0),
(24, 'yazar', 'yazar', 0),
(25, 'fatma şahin', 'fatma-sahin', 0),
(26, 'Karikatür', 'karikatur', 0),
(27, 'Sizden Gelenler', 'sizden-gelenler', 0),
(28, 'Şiirhane', 'siirhane', 0),
(29, 'papatya', 'papatya', 0),
(30, 'Doga', 'doga', 0),
(31, 'Down sendromu', 'down-sendromu', 0),
(32, 'Tenis', 'tenis', 0),
(33, 'Kübra Kızıltoprak', 'kubra-kiziltoprak', 0),
(34, 'şiir', 'siir', 0),
(35, 'Şiirhane', 'siirhane', 0),
(36, 'Fmf Kapın', 'fmf-kapin', 0),
(37, 'Kapının Arkasındakiler', 'kapinin-arkasindakiler', 0),
(38, 'çiçek', 'cicek', 0),
(39, 'şirr', 'sirr', 0),
(40, 'küflü sayfam', 'kuflu-sayfam', 0),
(41, 'ayrılık', 'ayrilik', 0),
(42, 'ACININ DEĞERİ', 'acinin-degeri', 0),
(43, 'yazı', 'yazi', 0),
(44, 'sevemedim', 'sevemedim', 0),
(45, 'AYRILIK UĞURU', 'ayrilik-uguru', 0),
(46, 'Gitmeyi Beklemek', 'gitmeyi-beklemek', 0),
(47, 'Kanatsız Doğmuş Kuşlar', 'kanatsiz-dogmus-kuslar', 0),
(48, 'BİR PAPATYA’NIN DOĞA’DA VAR OLUŞ HİKAYESİ', 'bir-papatyanin-dogada-var-olus-hikayesi', 0),
(49, 'Dar Yollarda Çiçek Açar mı?', 'dar-yollarda-cicek-acar-mi', 0),
(50, 'Taş Denilen Çiçekler De Açıyorsa Dünya’da', 'tas-denilen-cicekler-de-aciyorsa-dunyada', 0),
(51, 'Otizm', 'otizm', 0),
(52, 'Yusuf karaman', 'yusuf-karaman', 0),
(53, 'Zeynep Karaman', 'zeynep-karaman', 0),
(54, 'milli takım', 'milli-takim', 0),
(55, 'Gülerken Aglayanlar', 'gulerken-aglayanlar-2', 0),
(56, 'Arafta Kalan Kahkahalar', 'arafta-kalan-kahkahalar', 0),
(57, 'Ömer Faruk Kotay', 'omer-faruk-kotay', 0),
(58, 'Güreş', 'gures', 0),
(59, 'Hakem', 'hakem', 0),
(60, 'Gureş Hakemi', 'gures-hakemi', 0),
(61, 'Furkan Altunışık', 'furkan-altunisik', 0),
(62, 'Güreş Hakemi', 'gures-hakemi-2', 0),
(63, 'msal Başkan Saral', 'msal-baskan-saral', 0),
(64, 'Emsal Başkan Saral', 'emsal-baskan-saral', 0),
(65, 'Ailevi Akdeniz Ateşi', 'ailevi-akdeniz-atesi', 0),
(66, 'Behçet ve Ailevi Akdeniz Ateşi Derneği', 'behcet-ve-ailevi-akdeniz-atesi-dernegi', 0),
(67, 'Behçet', 'behcet', 0),
(68, 'Ailesel Akdeniz Ateşi', 'ailesel-akdeniz-atesi', 0),
(69, 'Fahriye Kılıç', 'fahriye-kilic', 0),
(70, 'Tayfur Abbasoğulları', 'tayfur-abbasogullari', 0),
(71, 'Bir Hayatın Bir Ailenin Bir Ömrün Hikâyesi', 'bir-hayatin-bir-ailenin-bir-omrun-hikayesi', 0),
(72, 'Vira Bismillah', 'vira-bismillah', 0),
(73, 'Hayatın Engelsiz Tarafı', 'hayatin-engelsiz-tarafi', 0),
(74, 'www.hayattan.net', 'www-hayattan-net', 0),
(75, 'Hayatın Engelsiz Tarafı Www.hayattan.net', 'hayatin-engelsiz-tarafi-www-hayattan-net', 0),
(76, 'engel', 'engel', 0),
(77, 'Engelsiz Şahsiyetler', 'engelsiz-sahsiyetler', 0),
(78, 'Timur', 'timur', 0),
(79, 'Aşık Veysel', 'asik-veysel', 0),
(80, 'Uzun İnce Bir Yoldayım', 'uzun-ince-bir-yoldayim', 0),
(81, 'Dostlar Beni Hatırlasın', 'dostlar-beni-hatirlasin', 0),
(82, 'Aşık Veysel Şatıroğlu', 'asik-veysel-satiroglu', 0),
(83, 'Cemil Meriç', 'cemil-meric', 0),
(84, 'Thomas Alva', 'thomas-alva', 0),
(85, 'Thomas Alva Edison', 'thomas-alva-edison', 0),
(86, 'Ludwig Van Beethoven', 'ludwig-van-beethoven', 0),
(87, 'engelsiz', 'engelsiz', 0),
(88, 'VAR MISIN', 'var-misin', 0),
(89, 'VAR MISIN -1', 'var-misin-1', 0),
(90, 'Erzurum Şampiyon Güreşçiler Derneği', 'erzurum-sampiyon-guresciler-dernegi', 0),
(91, 'Erzurum İl Başkanı Fatih Hikmet Sevim', 'erzurum-il-baskani-fatih-hikmet-sevim', 0),
(92, 'Doç Dr izzet uçan', 'doc-dr-izzet-ucan', 0),
(93, 'İzzet Uçar', 'izzet-ucar', 0),
(94, 'İzzet Uçan', 'izzet-ucan', 0),
(95, 'Dünya Gençlik ve Spor Konfederasyonu', 'dunya-genclik-ve-spor-konfederasyonu', 0),
(96, 'Dünya Gençlik ve Spor Konfederasyonu Erzurum İl Başkanı', 'dunya-genclik-ve-spor-konfederasyonu-erzurum-il-baskani', 0),
(97, 'Fatih Hikmet Sevim', 'fatih-hikmet-sevim', 0),
(98, 'HAYATA KARIŞMAK', 'hayata-karismak', 0),
(99, 'Hayattan.net', 'hayattan-net', 0),
(100, 'CHRİSTY BROWN', 'christy-brown', 0),
(101, 'STEPHEN HAWKİNG', 'stephen-hawking', 0),
(102, 'Charcot', 'charcot', 0),
(103, 'ALS', 'als', 0),
(104, 'Stephen William Hawking', 'stephen-william-hawking', 0),
(105, 'kara delik', 'kara-delik', 0),
(106, 'büyük patlama', 'buyuk-patlama', 0),
(107, 'İngiliz fizikçi ve evrenbilimci', 'ingiliz-fizikci-ve-evrenbilimci', 0),
(108, 'ngiliz fizikçi ve evrenbilimci', 'ngiliz-fizikci-ve-evrenbilimci', 0),
(109, 'astronom', 'astronom', 0),
(110, 'teorisyen', 'teorisyen', 0),
(111, 'astrofizik', 'astrofizik', 0),
(112, 'kozmoloji', 'kozmoloji', 0),
(113, 'teorik fizik', 'teorik-fizik', 0),
(114, 'teori', 'teori', 0),
(115, 'fizik', 'fizik', 0),
(116, 'ressam', 'ressam', 0),
(117, 'Christy Brown', 'christy-brown-2', 0),
(118, 'Sol Ayağım', 'sol-ayagim', 0),
(119, 'beyin felci', 'beyin-felci', 0),
(120, 'Her Gün Hüzün', 'her-gun-huzun', 0),
(121, 'Sol Ayağım-1', 'sol-ayagim-1', 0),
(122, 'Sol Ayağım-2', 'sol-ayagim-2', 0),
(123, 'VAR MISIN 2', 'var-misin-2', 0),
(124, 'Hakemlik Kursu', 'hakemlik-kursu', 0),
(125, 'Edzurum', 'edzurum', 0),
(126, 'Erzurum', 'erzurum', 0),
(127, 'Güreş Hakemliği Kursu', 'gures-hakemligi-kursu', 0),
(128, 'Engelli Güreş Hakemi', 'engelli-gures-hakemi', 0),
(129, 'KAFAMDAKİ SORULAR', 'kafamdaki-sorular', 0),
(130, 'Lokman Ayva', 'lokman-ayva', 0),
(131, 'Eşref Armağan', 'esref-armagan', 0),
(132, 'Görme Engelli Milletvekili', 'gorme-engelli-milletvekili', 0),
(133, 'Avrupa Konseyi Parlamenterler Meclisi', 'avrupa-konseyi-parlamenterler-meclisi', 0),
(134, 'TBMM&#039;

INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(980, 'tuğladan örülmüş ve içinde çeşitli bahçe bitkileri ile çiçekler bulunan bir saksı vardı. Bitkilerin yaprakları birbirine karışmış', 'tugladan-orulmus-ve-icinde-cesitli-bahce-bitkileri-ile-cicekler-bulunan-bir-saksi-vardi-bitkilerin-yapraklari-birbirine-karismis', 0),
(981, 'yer yer kurumuştu. Kapının hemen üstünde bulunan sac levhada', 'yer-yer-kurumustu-kapinin-hemen-ustunde-bulunan-sac-levhada', 0),
(982, 'saç kesme makasları', 'sac-kesme-makaslari', 0),
(983, 'tarak', 'tarak', 0),
(984, 'Günaydın', 'gunaydin', 0),
(985, 'Tercüman', 'tercuman', 0),
(986, 'Tan ve Bulvar gazeteleri ile Gırgır dergisi bulunuyordu. Ayrıca', 'tan-ve-bulvar-gazeteleri-ile-girgir-dergisi-bulunuyordu-ayrica', 0),
(987, 'Brain Adams', 'brain-adams', 0),
(988, 'Müslüm Gürses', 'muslum-gurses', 0),
(989, 'tezgâh', 'tezgah', 0),
(990, 'sehpanın üzerinde içinde iki tane filtreli sigara izmariti bulunan bir küllük duruyordu. Dipteki tezgâhın yanında kaset çalar ve duvara monte rafta Orhan Gencebay', 'sehpanin-uzerinde-icinde-iki-tane-filtreli-sigara-izmariti-bulunan-bir-kulluk-duruyordu-dipteki-tezgahin-yaninda-kaset-calar-ve-duvara-monte-rafta-orhan-gencebay', 0),
(991, 'Modern Talking ve isimsiz doldurma kasetler diziliydi. Aynalar', 'modern-talking-ve-isimsiz-doldurma-kasetler-diziliydi-aynalar', 0),
(992, 'koltuk ve bekleme sandalyeleri toz içindeydi. Aynada', 'koltuk-ve-bekleme-sandalyeleri-toz-icindeydi-aynada', 0),
(993, 'tezgâhta ve lavaboda kurumuş kan lekeleri vardı. Lavabo içinde bir ustura duruyor', 'tezgahta-ve-lavaboda-kurumus-kan-lekeleri-vardi-lavabo-icinde-bir-ustura-duruyor', 0),
(994, 'tavan köşelerinde örümcek ağları oluşmuş', 'tavan-koselerinde-orumcek-aglari-olusmus', 0),
(995, 'HEY GİDİ GÜNLER!', 'hey-gidi-gunler', 0),
(996, 'KIRILMIŞLIKLARIM', 'kirilmisliklarim', 0),
(997, 'Zindan Adası', 'zindan-adasi', 0),
(998, 'Engelsiz Filmler Festivali Direktörü EZGİ YALINALP', 'engelsiz-filmler-festivali-direktoru-ezgi-yalinalp', 0),
(999, 'Engelsiz Filmler Festivali', 'engelsiz-filmler-festivali', 0),
(1000, 'Sinema', 'sinema', 0),
(1001, 'Festival', 'festival', 0),
(1002, 'Erişilebilirlik', 'erisilebilirlik', 0),
(1003, 'flim', 'flim', 0),
(1004, 'Döngüyü Kırmak Erişilebilir Sinema', 'donguyu-kirmak-erisilebilir-sinema', 0),
(1005, 'SENİ SEVİYOR MUSUN?', 'seni-seviyor-musun', 0),
(1006, 'Kendini Sev', 'kendini-sev', 0),
(1007, 'FOTOĞRAFHANE-11', 'fotografhane-11', 0),
(1008, 'Denizli', 'denizli', 0),
(1009, 'Özlem Ürekli', 'ozlem-urekli', 0),
(1010, 'UMUDUM VAR!', 'umudum-var', 0),
(1011, 'Otizim', 'otizim', 0),
(1012, 'RaDiChal’21 Projesi', 'radichal21-projesi', 0),
(1013, 'Fmf Force', 'fmf-force', 0),
(1014, 'DIŞARIDAKİLER', 'disaridakiler', 0),
(1015, 'Glikojen Depo Hastalıkları Temsilcisi', 'glikojen-depo-hastaliklari-temsilcisi', 0),
(1016, 'COST GSD Türkiye Temsilcisi', 'cost-gsd-turkiye-temsilcisi', 0),
(1017, 'GSD', 'gsd', 0),
(1018, 'COST GSD Türkiye', 'cost-gsd-turkiye', 0),
(1019, 'Ekonomist', 'ekonomist', 0),
(1020, 'Sosyolog', 'sosyolog', 0),
(1021, 'FOTOĞRAFHANE-12', 'fotografhane-12', 0),
(1022, 'SENİ SEVİYOR MUSUN?-2', 'seni-seviyor-musun-2', 0),
(1023, 'FOTOĞRAFHANE-13', 'fotografhane-13', 0),
(1024, 'AH BE ZÜLEYHA!', 'ah-be-zuleyha', 0),
(1025, 'Bir Demet Tiyatro', 'bir-demet-tiyatro', 0),
(1026, 'Eyvah Necdet', 'eyvah-necdet', 0),
(1027, 'Şubat ayı olağan değerlendirme toplantısı', 'subat-ayi-olagan-degerlendirme-toplantisi', 0),
(1028, 'ENGELSİZ ŞAHSİYETLER-55', 'engelsiz-sahsiyetler-55', 0),
(1029, 'Ressam Yusuf Akgün', 'ressam-yusuf-akgun', 0),
(1030, 'Yusuf Akgün', 'yusuf-akgun', 0),
(1031, 'YOLDAKİLER', 'yoldakiler', 0),
(1032, 'UFKA GİDEN KADIN-3', 'ufka-giden-kadin-3', 0),
(1033, 'Yahya Kemal Beyatlı', 'yahya-kemal-beyatli', 0),
(1034, 'EY İSTANBUL!', 'ey-istanbul', 0),
(1035, 'FOTOĞRAFHANE-14', 'fotografhane-14', 0),
(1036, 'ÇEKMECEMDEKİ MEKTUPLAR-3', 'cekmecemdeki-mektuplar-3', 0),
(1037, 'ENGELSİZ ŞAHSİYETLER-56', 'engelsiz-sahsiyetler-56', 0),
(1038, 'Fatih Karataş', 'fatih-karatas', 0),
(1039, 'engelli tenisçi', 'engelli-tenisci', 0),
(1040, 'Ankara il Engelli Meclisi Başkanı', 'ankara-il-engelli-meclisi-baskani', 0),
(1041, 'HAK MÜCADELESİ', 'hak-mucadelesi', 0),
(1042, 'Muhammed Veysi sayın', 'muhammed-veysi-sayin', 0),
(1043, 'Ankara il Engelli Meclisi Başkanı Muhammed Veysi sayın', 'ankara-il-engelli-meclisi-baskani-muhammed-veysi-sayin', 0),
(1044, 'Palio Sekeli', 'palio-sekeli', 0),
(1045, 'Veysi Sayın', 'veysi-sayin', 0),
(1046, 'KADIN ÖTESİ KADINLARA', 'kadin-otesi-kadinlara', 0),
(1047, '8 Mart Dünya Kadınlar Günü', '8-mart-dunya-kadinlar-gunu', 0),
(1048, 'Dünya Kadınlar Günü', 'dunya-kadinlar-gunu', 0),
(1049, '8 Mart', '8-mart', 0),
(1050, 'GEÇMİŞ OLSUN', 'gecmis-olsun', 0),
(1051, 'YENİDEN DOĞUŞUN MISRALARI', 'yeniden-dogusun-misralari', 0),
(1052, 'CUMA KÖSE', 'cuma-kose', 0),
(1053, 'Mehmet Akif Ersoy', 'mehmet-akif-ersoy', 0),
(1054, '12 mart istiklal marşının kabulü', '12-mart-istiklal-marsinin-kabulu', 0),
(1055, 'İstiklal marşının kabulü', 'istiklal-marsinin-kabulu', 0),
(1056, 'İstiklal Marşı', 'istiklal-marsi', 0),
(1057, 'BEKLEMEYE GELMEZ', 'beklemeye-gelmez', 0),
(1058, 'BaKıŞ', 'bakis', 0),
(1059, 'İNSANA HAYATA EDEBİYATA BAKIŞ', 'insana-hayata-edebiyata-bakis', 0),
(1060, 'E-DERGİ', 'e-dergi', 0),
(1061, 'İnsana Hayata Edebiyata Bakış', 'insana-hayata-edebiyata-bakis-2', 0),
(1062, 'Kültür-Sanat', 'kultur-sanat', 0),
(1063, 'Çınar Can Özyürek', 'cinar-can-ozyurek', 0),
(1064, 'Dergi', 'dergi', 0),
(1065, 'BaKıŞ İnsana Hayata Edebiyata Bakış', 'bakis-insana-hayata-edebiyata-bakis', 0),
(1066, 'BaKıŞ Dergisi', 'bakis-dergisi', 0),
(1067, 'SİZCE HANGİMİZ ENGELLİYİZ?', 'sizce-hangimiz-engelliyiz', 0),
(1068, 'ÇINAR CAN ÖZYÜREK', 'cinar-can-ozyurek-2', 0),
(1069, 'BEFEMDER', 'befemder', 0),
(1070, 'Ankara', 'ankara', 0),
(1071, 'BİR ANKARA VARDI', 'bir-ankara-vardi', 0),
(1072, 'BENLİĞİMİZİ KAYBETTİREN TEKNOLOJİ', 'benligimizi-kaybettiren-teknoloji', 0),
(1073, 'TEKNOLOJİ', 'teknoloji', 0),
(1074, 'ENGELSİZ ŞAHSİYETLER-57', 'engelsiz-sahsiyetler-57', 0),
(1075, 'parapleji', 'parapleji', 0),
(1076, 'Merve Nur Eroğlu', 'merve-nur-eroglu', 0),
(1077, 'Spor Engel Tanımaz', 'spor-engel-tanimaz', 0),
(1078, 'Bedensel Engelliler Türkiye Şampiyonası', 'bedensel-engelliler-turkiye-sampiyonasi', 0),
(1079, 'Avrupa Para Okçuluk Şampiyonası', 'avrupa-para-okculuk-sampiyonasi', 0),
(1080, 'YANLIŞ ANLADIK', 'yanlis-anladik', 0),
(1081, 'Mart ayı olağan değerlendirme toplantısı', 'mart-ayi-olagan-degerlendirme-toplantisi', 0),
(1082, 'SORUMSUZ NESİLLER', 'sorumsuz-nesiller', 0),
(1083, 'Sorumluluk', 'sorumluluk', 0),
(1084, 'Nesil', 'nesil', 0),
(1085, 'Yeni Nesil', 'yeni-nesil', 0),
(1086, 'ÇINAR CAN ÖZYÜREK İN OBJEKTİFİNDEN', 'cinar-can-ozyurek-in-objektifinden', 0),
(1087, 'FOTOĞRAFHANE -15', 'fotografhane-15', 0),
(1088, 'ENGELSİZ ŞAHSİYETLER-58', 'engelsiz-sahsiyetler-58', 0),
(1089, 'Baxter Humby', 'baxter-humby', 0),
(1090, 'kick boks', 'kick-boks', 0),
(1091, 'EY İSTANBUL 2', 'ey-istanbul-2', 0),
(1092, 'ÖZEL VE GÜZEL', 'ozel-ve-guzel', 0),
(1093, '11 Ayın Sultanı', '11-ayin-sultani', 0),
(1094, 'FOTOĞRAFHANE-16', 'fotografhane-16', 0),
(1095, 'HANİ GELİŞİM?', 'hani-gelisim', 0),
(1096, 'Kişisel Gelişim', 'kisisel-gelisim', 0),
(1097, 'Bireysel Gelişim', 'bireysel-gelisim', 0),
(1098, 'Gelişim', 'gelisim', 0),
(1099, 'Hayatın Engelsiz Tarafı www.hayattan.net Genel Sorumlusu Ömer Faruk Kotay&#039;

